### ISSUE TITLE
 I want to contribute to this project.

### ISSUE THREAD

**Issue by vivek80801** [eddiejaoude/rock-paper-scissors-game#8]
Hello sir,

I am new to github and highly inspired by your youtube videos.

I want to contribute to open source. I want to contribute to this project.

Can I create this game with React.js and typescript in different branch ?

**Comment by eddiejaoude** [comment]
Hi @vivek80801 ,

Thank you for your positive feedback.

Sure, if you want to do a `react` version in a branch and it can be used as a comparison 👍

**Comment by vivek80801** [comment]
@eddiejaoude  sir,

can you review my pull request draft #11 ?

**Comment by eddiejaoude** [comment]
Sure 👍
